name: 'CD -> Release'
on:
    workflow_dispatch:
    push:
        branches:
            - stable

jobs:
    release:
        name: 'Release to npm'
        runs-on: ubuntu-latest
        permissions:
            id-token: write

        steps:
            - name: 'Checkout'
              uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
              with:
                  persist-credentials: false

            - name: 'Setup Bun'
              uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2

            - name: 'Install dependencies'
              run: bun i

            - name: 'Install npm'
              run: bun install -g npm

            - name: 'List files'
              run: ls -la

            - name: 'Build and Publish'
              run: bunx --bun npm publish --provenance --tag latest
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
